<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_model extends CI_Model
{

    public $table = 'barang,barang_masuk';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // // get all
    // function get_all()
    // {
    //     $this->db->order_by($this->id, $this->order);
    //     return $this->db->get($this->table)->result();
    // }
// 
    // // get data by id
    // function get_by_id($id)
    // {
    //     $this->db->where($this->id, $id);
    //     return $this->db->get($this->table)->row();
    // }
    
    // get total rows
    function total_rows($q = NULL) {
            $this->db->select('*');
            $this->db->from('barang,barang_masuk ma,barang_keluar ke');
             $this->db->where('ma.kode_barang=ke.kode_barang');

          //  $this->db->join('barang_keluar');
        // $this->db->like('id_barang', $q);
    // $this->db->or_like('kode_barang', $q);
    // $this->db->or_like('nama_barang', $q);
    // $this->db->or_like('stok', $q);
   // $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
         $this->db->select('*');
            $this->db->from('barang,barang_masuk ma,barang_keluar ke');
 $this->db->where('ma.kode_barang=ke.kode_barang');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang', $q);
    // $this->db->or_like('kode_barang', $q);
    // $this->db->or_like('nama_barang', $q);
    // $this->db->or_like('stok', $q);
    $this->db->limit($limit, $start);
        // return $this->db->get($this->table)->result();
    $q=$this->db->get();
    return $q->result();
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:51 */
/* http://harviacode.com */